---
- name: Provison EC2 Instance for Tomcat
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: create EC2 key pair
    ec2_key:
      name: keypair_student
      state: present
    register: ec2_keys

#  - debug:
#      var: ec2_keys

  - name: copy the key to file
    copy:
      content: "{{ ec2_keys.key.private_key }}"
      dest: /home/ec2-user/keypair_student.pem
      owner: ec2-user
      group: ec2-user
      mode: 0400
    when:
      - not ansible_check_mode
      - ec2_keys.changed
#    register: keys_out

#  - debug:
#      var: key_out

  - name: Create EC2 Security Groups
    ec2_group:
      name: aws_security_group.student-sg
      description: aws_security_group.student-sg
      vpc_id: vpc-06606070944ec2cf8
      state: present
      rules:       # List of firewall inbound rules
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
          rule_desc: SSH
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
          rule_desc: Jenkins Console
      rules_egress:     # List of firewall outbound rules
          - proto: all
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow all outbound traffic
    register: ec2_sg

#  - debug:
#      var: ec2_sg

  - name: start an instance
    ec2:
      vpc_subnet_id: subnet-0d2cfafc75b306ed5
      region: us-east-1
      instance_type: t3.micro
      image: ami-0c2b8ca1dad447f8a
      key_name: "{{ ec2_keys.key.name }}" 
      group_id: "{{ ec2_sg.group_id }}"
      user_data: "{{ lookup('file', 'install_jenkin_ansible_maven.sh') }}"
#    when:
#      - ec2_keys.changed
#      - ec2_sg.changed
#      - not ansible_check_mode
#    register: ec2_instance

#  - debug:
#      var: ec2_instance
