---
- hosts: webserver
  become: true
  gather_facts: false
  tasks:

  - name: Deploy bookzy_webapp package to Tomcat Webserver
    copy: 
      src: /var/lib/jenkins/workspace/bookzy_webapp/target/bookzy_webapp-0.0.1-SNAPSHOT.war
      dest: /opt/tomcat/webapps/bookzy_webapp.war
      owner: tomcat
      group: tomcat        
      mode: 0640
