---
- name: Provison EC2 Instance for Jenkin and Ansible
  hosts: webserver
#  connection: local
  gather_facts: true
  become: True
  become_user: root
  become_method: sudo
  tasks:

  - name: yum repo add
    yum_repository:
      name: jenkins.repo
      description: Jenkin Repo
#      baseurl: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      baseurl: https://pkg.jenkins.io/redhat-stable/

  - name: import Jenkin key
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

  - name: install Jenkin and git
    yum:
      name: "{{ item }}"
      state: latest
    loop:
      - java
      - git
      - jenkins
      - maven

  - name: install ansible
    shell: /usr/bin/amazon-linux-extras install ansible2 -y

#  - name: download Install maven
#    ansible.builtin.unarchive:
#      src: https://apache.claz.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
#      dest: /tmp
#      remote_src: yes
