---
- name: Provison EC2 Instance for Tomcat Webserver
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Create EC2 key pair
    ec2_key:
      name: keypair_tomcat
      state: present
    register: ec2_keys

  - name: Copy private key to file
    copy:
      content: "{{ ec2_keys.key.private_key }}"
      dest: /home/ec2-user/keypair_tomcat.pem
      owner: ec2-user
      group: ec2-user
      mode: 0400
    when:
      - not ansible_check_mode
      - ec2_keys.changed

  - name: Create EC2 Security Groups
    ec2_group:
      name: aws_security_group.tomcat-sg
      description: aws_security_group.tomcat-sg
      vpc_id: vpc-0e81560a0b96cb943
      state: present
      rules:       # List of firewall inbound rules
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
          rule_desc: SSH
        - proto: tcp
          from_port: 8080
          to_port: 8080
          cidr_ip: 0.0.0.0/0
          rule_desc: Tomcat
      rules_egress:     # List of firewall outbound rules
          - proto: all
            cidr_ip: 0.0.0.0/0
            rule_desc: Allow all outbound traffic
    register: ec2_sg

  - name: Start EC2 Instance
    ec2:
      vpc_subnet_id: subnet-0596b9e3c80d0512d
      region: us-east-1
      instance_type: t3.micro
      image: ami-0c2b8ca1dad447f8a
      key_name: "{{ ec2_keys.key.name }}" 
      group_id: "{{ ec2_sg.group_id }}"
      user_data: "{{ lookup('file', 'install_tomcat.sh') }}"
